name: Docker Image CI

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        TIMESTAMP=$(date +%Y%m%d)
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/instock:latest
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/instock:latest ${{ secrets.DOCKERHUB_USERNAME }}/instock:$TIMESTAMP
    
    - name: Push Docker image to Docker Hub
      run: |
        TIMESTAMP=$(date +%Y%m%d)
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/instock:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/instock:$TIMESTAMP
